package kube

import (
	"context"
	"errors"
	"fmt"
	"github.com/codefresh-io/argocd-listener/controller/pkg/kube/kubeobj"
	"github.com/codefresh-io/argocd-listener/controller/pkg/logger"
	"io/ioutil"
	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/api/core/v1"
	apixv1beta1client "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1"
	k8sErrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	_ "k8s.io/client-go/plugin/pkg/client/auth"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"
	"net/http"
	"reflect"
	"strconv"
	"strings"
)

type (
	Kube interface {
		buildClient() (*kubernetes.Clientset, *apixv1beta1client.ApiextensionsV1beta1Client, error)
		GetNamespaces() ([]string, error)
		CreateNamespace(string) error
		GetService(string) (*v1.Service, error)
		UpdateService(*v1.Service) error
		GetAutogeneratedPassword() (string, error)
		UpdateDeployments(*appsv1.DeploymentList) error
		GetDeployments(string) (*appsv1.DeploymentList, error)
		CreateObjects(string) error

		DeleteObjects(string) error
		GetArgoServerHost() (string, error)
	}

	kube struct {
		contextName      string
		namespace        string
		pathToKubeConfig string
		clientSet        *kubernetes.Clientset
		crdClientSet     *apixv1beta1client.ApiextensionsV1beta1Client
		ctx              context.Context
	}

	Options struct {
		ContextName      string
		Namespace        string
		PathToKubeConfig string
	}
)

func New(o *Options) (Kube, error) {
	client := &kube{
		contextName:      o.ContextName,
		namespace:        o.Namespace,
		pathToKubeConfig: o.PathToKubeConfig,
		ctx:              context.Background(),
	}
	clientSet, crdClientSet, err := client.buildClient()

	if err != nil {
		return nil, err
	}

	client.clientSet = clientSet
	client.crdClientSet = crdClientSet

	return client, nil
}
func GetAllContexts(pathToKubeConfig string) ([]string, error) {
	var result []string
	k8scmd := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: pathToKubeConfig},
		&clientcmd.ConfigOverrides{})

	config, err := k8scmd.RawConfig()

	if err != nil {
		return result, err
	}

	if config.CurrentContext != "" {
		result = append(result, config.CurrentContext)
	}

	for k, _ := range config.Contexts {
		if k == config.CurrentContext {
			continue
		}

		result = append(result, k)
	}

	return result, err
}

func (k *kube) CreateNamespace(namespaceName string) error {
	namespace, err := k.clientSet.CoreV1().Namespaces().Get(namespaceName, metav1.GetOptions{})

	if namespace != nil && namespace.Status.Phase == "Active" {
		k.namespace = namespaceName
		return nil
	}

	var namespaceObj = v1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: k.namespace,
		},
	}
	_, err = k.clientSet.CoreV1().Namespaces().Create(&namespaceObj)
	return err
}

func (k *kube) buildClient() (*kubernetes.Clientset, *apixv1beta1client.ApiextensionsV1beta1Client, error) {
	var config *rest.Config
	var err error
	config, err = clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: k.pathToKubeConfig},
		&clientcmd.ConfigOverrides{
			CurrentContext: k.contextName,
			Context: clientcmdapi.Context{
				Namespace: k.namespace,
			},
		}).ClientConfig()

	if err != nil {
		return nil, nil, err
	}
	clientSet, err := kubernetes.NewForConfig(config)
	apixClient, err := apixv1beta1client.NewForConfig(config)

	return clientSet, apixClient, err
}

func (k *kube) GetService(labelSelector string) (*v1.Service, error) {
	var argoServerSvc v1.Service
	opts := metav1.ListOptions{LabelSelector: labelSelector}

	svcs, err := k.clientSet.CoreV1().Services(k.namespace).List(opts)

	if err != nil {
		return &argoServerSvc, err
	}
	if svcs == nil || len(svcs.Items) == 0 {
		return &argoServerSvc, errors.New(fmt.Sprint("Invalid svcs"))
	}

	return &svcs.Items[0], nil
}

func (k *kube) GetDeployments(labelSelector string) (*appsv1.DeploymentList, error) {
	return kubeobj.GetDeployments(k.clientSet, k.namespace, labelSelector)
}

func (k *kube) UpdateService(svc *v1.Service) error {
	_, err := k.clientSet.CoreV1().Services(k.namespace).Update(svc)
	return err
}

func (k *kube) UpdateDeployments(deploymentList *appsv1.DeploymentList) error {
	for _, deployment := range deploymentList.Items {
		_, err := kubeobj.UpdateDeployment(k.clientSet, &deployment, k.namespace)
		if err != nil {
			return err
		}
	}
	return nil
}

func (k *kube) DeleteObjects(manifestPath string) error {
	var err error
	templatesMap, err := buildTemplatesFromManifest(manifestPath)
	if err != nil {
		return err
	}
	var templatesValues map[string]interface{}

	kubeObjects, _, err := BuildObjectsFromTemplates(templatesMap, templatesValues)
	if err != nil {
		return err
	}

	var kind, name string
	var deleteError error
	for _, obj := range kubeObjects {
		kind, name, deleteError = kubeobj.DeleteObject(k.clientSet, k.crdClientSet, obj, k.namespace)
		if deleteError == nil {
			fmt.Println(fmt.Sprintf("%s \"%s\" deleted", kind, name))
		} else if statusError, errIsStatusError := deleteError.(*k8sErrors.StatusError); errIsStatusError {
			if statusError.ErrStatus.Reason == metav1.StatusReasonNotFound {
				logger.Warning(fmt.Sprintf("Resource %s \"%s\" not found", kind, name))
			} else {
				return statusError
			}
		} else {
			return deleteError
		}
	}

	return nil
}

func (k *kube) CreateObjects(manifestPath string) error {
	var err error
	templatesMap, err := buildTemplatesFromManifest(manifestPath)
	if err != nil {
		return err
	}
	var templatesValues map[string]interface{}

	kubeObjects, _, err := BuildObjectsFromTemplates(templatesMap, templatesValues)
	if err != nil {
		return err
	}

	kubeObjectKeys := reflect.ValueOf(kubeObjects).MapKeys()

	for _, key := range kubeObjectKeys {
		kind, name, createErr := kubeobj.CreateObject(k.clientSet, k.crdClientSet, kubeObjects[key.String()], k.namespace)

		if createErr == nil {
			// skip, everything ok
		} else if statusError, errIsStatusError := createErr.(*k8sErrors.StatusError); errIsStatusError {
			if statusError.ErrStatus.Reason == metav1.StatusReasonAlreadyExists {
				logger.Warning(fmt.Sprintf("%s \"%s\" already exists", kind, name))
			} else {
				logger.Error(fmt.Sprintf("%s \"%s\" failed: %v ", kind, name, statusError))
				return statusError
			}
		} else {
			logger.Error(fmt.Sprintf("%s \"%s\" failed: %v ", kind, name, createErr))
			return createErr
		}
	}
	return err
}

func buildTemplatesFromManifest(manifestPath string) (map[string]string, error) {
	var templatesMap = map[string]string{}
	var manifestByte []byte
	var err error
	if strings.HasPrefix(manifestPath, "http://") || strings.HasPrefix(manifestPath, "https://") {
		manifestByte, err = downloadManifest(manifestPath)
	} else {
		manifestByte, err = ioutil.ReadFile(manifestPath)
	}
	if err != nil {
		return templatesMap, err
	}
	templates := strings.Split(string(manifestByte), "\n---\n")
	for n, tpl := range templates {
		templatesMap["template_"+strconv.Itoa(n)+".yaml"] = tpl
	}
	return templatesMap, err
}

func (k *kube) GetArgoServerHost() (string, error) {
	opts := metav1.ListOptions{LabelSelector: "app.kubernetes.io/name=argocd-server"}
	svcs, err := k.clientSet.CoreV1().Services(k.namespace).List(opts)

	if err != nil {
		return "", err
	}
	if svcs == nil || len(svcs.Items) == 0 {
		return "", errors.New(fmt.Sprint("Invalid svcs"))
	}
	svc := svcs.Items[0]
	ingresses := svc.Status.LoadBalancer.Ingress
	if len(ingresses) == 0 {
		return "", errors.New("ingress not exist")
	}

	ingress := ingresses[0]

	if ingress.Hostname != "" {
		return "https://" + ingress.Hostname, nil
	}
	if ingress.IP != "" {
		return "https://" + ingress.IP, nil
	}

	return "", errors.New(fmt.Sprint("Can't resolve Ingress Hostname or IP"))
}

func (k *kube) GetAutogeneratedPassword() (string, error) {
	opts := metav1.ListOptions{LabelSelector: "app.kubernetes.io/name=argocd-server"}
	podsList, err := k.clientSet.CoreV1().Pods(k.namespace).List(opts)
	if err != nil {
		return "", err
	}
	return podsList.Items[0].ObjectMeta.Name, nil
}

func (k *kube) GetNamespaces() ([]string, error) {
	namespaces, err := k.clientSet.CoreV1().Namespaces().List(metav1.ListOptions{})

	if err != nil {
		return nil, err
	}

	var result []string

	for _, value := range namespaces.Items {
		if value.Name == "default" {
			result = append([]string{"default"}, result...)
			continue
		}
		result = append(result, value.Name)
	}

	return result, nil
}

func downloadManifest(url string) ([]byte, error) {
	response, err := http.Get(url)
	if err != nil {
		return []byte{}, err
	}
	defer response.Body.Close()
	return ioutil.ReadAll(response.Body)
}
