apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cf-argocd-agent
  name: cf-argocd-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-argocd-agent
subjects:
  - kind: ServiceAccount
    name: cf-argocd-agent
    namespace: {{ .Namespace }}