apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cf-argocd-agent
  name: cf-argocd-agent
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: cf-argocd-agent
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cf-argocd-agent
    spec:
      serviceAccountName: cf-argocd-agent
      containers:
      - env:
        - name: ARGO_HOST
          value: {{ .Argo.Host }}
        - name: ARGO_USERNAME
          value: {{ .Argo.Username }}
        - name: ARGO_PASSWORD
          value: {{ .Argo.Password }}
        - name: ARGO_TOKEN
          valueFrom:
            secretKeyRef:
              name: cf-argocd-agent
              key: argo.token
        - name: CODEFRESH_HOST
          value: {{ .Codefresh.Host }}
        - name: CODEFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: cf-argocd-agent
              key: codefresh.token
        - name: IN_CLUSTER
          value: "true"
        - name: AUTO_SYNC
          value: "{{ .Codefresh.AutoSync }}"
        - name: CODEFRESH_INTEGRATION
          value: {{ .Codefresh.Integration }}
        image: codefresh/argocd-agent:stable
        imagePullPolicy: Always
        name: cf-argocd-agent
      restartPolicy: Always